name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::jupyterlab=3.0.12
  - conda-forge::seaborn=0.11.1
  - conda-forge::pandas=1.2.3
  - pip=20.3.3
  - conda-forge::pandas-profiling=2.11.0
  - conda-forge::pyarrow=2.0
  - pip:
      - wandb==0.12.17