name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - conda-forge::requests=2.24.0
  - conda-forge::mlflow=1.14.1
  - conda-forge::scikit-learn=0.24.1
  - pip:
      - wandb==0.12.17
      - git+https://github.com/dnassty/build-ml-pipeline-for-short-term-rental-prices#egg=wandb-utils&subdirectory=components
