name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::pandas=1.1.4
  - pip=20.3.3
  - conda-forge::mlflow=1.14.1
  - sconda-forge::cikit-learn=0.24.1
  - pip:
      - wandb==0.12.17
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
